### ISSUE TITLE
Key rotation

### ISSUE THREAD

**Issue by swapnilsvaidya** [Aiven-Open/encrypted-repository-opensearch#60]
Hi, Is there a way to support rotation of keys used for encrypting the snapshot
Also if we encrypt the snapshot using one key and then rotate the key, does it recognize the earlier snapshots?

**Comment by willyborankin** [comment]
Hi good questions:
> Is there a way to support rotation of keys used for encrypting the snapshot
 
so far no due to the limitation of the plugin interface
>   Also if we encrypt the snapshot using one key and then rotate the key, does it recognize the earlier snapshots?

same it supports only one key so far the reasons the same.

But since OpenSearch wants to use the plugin https://github.com/opensearch-project/OpenSearch/issues/5800
I'm planning to discuss with them a possibility to integrate it inside OpenSearch and in this case each snapshot will have
it own key.

**Comment by willyborankin** [comment]
wil be fixed in https://github.com/Aiven-Open/encrypted-repository-opensearch/pull/77
